RedHatInsights/astro-virtual-assistant-frontend

src/Components/AstroChat/AstroChat.tsx, src/Components/AstroChat/AstroChatSkeleton.tsx, src/SharedComponents/AstroVirtualAssistant/astro-virtual-assistant.scss
Jira: https://issues.redhat.com/browse/RHCLOUD-30748
=> convert layout to PF Card

src/Components/AstroChat/AstroChat.tsx, src/Components/AstroChat/AstroChatSkeleton.tsx, src/SharedComponents/AstroVirtualAssistant/astro-virtual-assistant.scss
Jira: https://issues.redhat.com/browse/RHCLOUD-30824
=> more styling cleanup

src/Components/AstroChat/AstroChat.tsx, src/Components/AstroChat/useAstro.ts
- but also, only set loading if there is an actual message
=> RHCLOUD-31574 Prevent from processing empty messages

src/Components/AstroChat/AstroChat.tsx
Depends: https://github.com/RedHatInsights/astro-virtual-assistant/pull/422
=> RHCLOUD-32255 Adding privacy statement as an alert

src/SharedComponents/AstroVirtualAssistant/AstroVirtualAssistant.tsx, src/SharedComponents/AstroVirtualAssistant/astro-virtual-assistant.scss
=> RHCLOUD-32398 Adjust UI to not be covered by Favoriting banner

src/SharedComponents/AstroVirtualAssistant/CommandMessageProcessor.tsx, src/types/index.d.ts
To test in stage, but what can go wrong?
=> Tour guide definition and window type override

src/SharedComponents/AstroVirtualAssistant/CommandMessageProcessor.tsx, src/SharedComponents/AstroVirtualAssistant/CommandProcessor/CreateServiceAccProcessor.ts, src/api/PostCreateServiceAccount.ts, src/api/PostManage2fa.ts
- Directly read the response from the request
=> Fix create service account

package-lock.json, package.json, src/Components/AstroChat/AstroChat.tsx, src/SharedComponents/AstroVirtualAssistant/AstroVirtualAssistant.tsx, src/SharedComponents/AstroVirtualAssistant/astro-virtual-assistant.scss
Follow-up to: https://github.com/patternfly/virtual-assistant/pull/22
=> Remove old header background styling

package-lock.json, package.json, src/Components/AstroChat/AstroChat.tsx, src/SharedComponents/AstroVirtualAssistant/astro-virtual-assistant.scss
Jira: https://issues.redhat.com/browse/RHCLOUD-33980
=> Bump VA version / cleanup styling

package-lock.json, package.json, src/Components/Message/AssistantMessageEntry.tsx, src/SharedComponents/AstroVirtualAssistant/astro-virtual-assistant.scss
- Use the new version
*clicks*
=> fix question labels

src/Components/icon-chatbot.tsx, src/assets/badge-icon.svg
Jira: https://issues.redhat.com/browse/RHCLOUD-32738
=> Animate ro-bert

src/Components/AstroChat/AstroChat.tsx
https://issues.redhat.com/browse/RHCLOUD-34240
=> Links in privacy banner

src/Components/Message/ThumbsMessageEntry.tsx, src/SharedComponents/AstroVirtualAssistant/astro-virtual-assistant.scss
Jira: https://issues.redhat.com/browse/RHCLOUD-34220
=> Update thumb styling

src/Components/AstroChat/AstroChat.tsx, src/SharedComponents/AstroVirtualAssistant/astro-virtual-assistant.scss
Jira: https://issues.redhat.com/browse/RHCLOUD-33981
Old
New
=> Welcome alert update

package-lock.json, package.json
Resolves: [RHCLOUD-34679](https://issues.redhat.com/browse/RHCLOUD-34679)
=> Update frontend-components-config package

src/Components/AstroChat/AstroChat.tsx
https://issues.redhat.com/browse/RHCLOUD-39418
=> Remove privacy links

src/v2/Components/AstroChat/useAstro.ts, src/v2/Components/Message/SystemMessageEntry.tsx
=> Append system message on undefined watson response

.gitmodules, .tekton/virtual-assistant-frontend-pull-request.yaml, .tekton/virtual-assistant-frontend-push.yaml
https://issues.redhat.com/browse/RHCLOUD-38217
=> Migrate frontend build to use shared Dockerfile

src/v2/Components/AstroChat/useAstro.ts, src/v2/SharedComponents/AstroVirtualAssistant/CommandMessageProcessor.tsx, src/v2/SharedComponents/AstroVirtualAssistant/CommandProcessor/CreateServiceAccProcessor.ts, src/v2/SharedComponents/AstroVirtualAssistant/CommandProcessor/FeedbackCommandProcessor.ts, src/v2/SharedComponents/AstroVirtualAssistant/CommandProcessor/ManageOrg2FaProcessor.ts, src/v2/SharedComponents/AstroVirtualAssistant/CommandProcessor/ThumbsCommandProcessor.ts, src/v2/api/PostTalk.ts, src/v2/types/Command.ts
- Reading in command args into dicts
- Using the correct var for command type (i.e. /tour, /redirect , etc.)
- Changed tour command to have a dict of more than one command for the future (with or without pendo)
=> Command v2 followup

src/v2/Components/Message/ThumbsMessageEntry.tsx
=> Hide thumbs up response

src/v2/SharedComponents/AstroVirtualAssistant/astro-virtual-assistant.scss
Jira: https://issues.redhat.com/browse/RHCLOUD-40173
=> Adding AI text to footer

cypress/components/useAstro.cy.tsx, src/v2/Components/AstroChat/useAstro.ts, src/v2/Components/Banners/RequestErrorBanner.tsx, src/v2/Components/Message/BannerEntry.tsx, src/v2/Components/Message/SystemMessageEntry.tsx, src/v2/SharedComponents/AstroVirtualAssistant/AstroVirtualAssistant.tsx
=> Handling erroring talk requests

cypress/components/AstroChat.cy.tsx, src/Config.ts, src/v2/Components/AstroChat/AstroChat.tsx, src/v2/Components/Message/AssistantMessageEntry.tsx, src/v2/Components/Message/LingeringThumbsButtons.tsx
https://redhat-internal.slack.com/archives/C0548A5QYJW/p1749158930015999?thread_ts=1748528648.251229&cid=C0548A5QYJW
=> Thumb feedback options on each message

src/v2/Components/Message/LingeringThumbsButtons.tsx, src/v2/SharedComponents/AstroVirtualAssistant/astro-virtual-assistant.scss
Jira: https://issues.redhat.com/browse/RHCLOUD-40507
Old
New
=> Feedback thumbs fix

src/SharedComponents/AstroVirtualAssistant/AstroVirtualAssistant.tsx
Ensure the showAssistant prop is honored
=> fix: handle show assistant from parent component

ARH_CHATBOT_TESTING_GUIDE.md, cypress/components/ARHBadge.cy.tsx, src/Components/ARHClient/ARHBadge.scss, src/Components/ARHClient/ARHBadge.tsx, src/Components/ARHClient/ARHFooter.tsx, src/Components/ARHClient/ARHHeader.scss, src/Components/ARHClient/ARHHeader.tsx
Jira: https://issues.redhat.com/browse/RHCLOUD-41455
- added footer note
- reduce the header padding
=> fix: address UX visual feedback

ONBOARDING_GUIDE.md, README.md
Code references will match once the VA PR is merged: https://github.com/RedHatInsights/astro-virtual-assistant-frontend/pull/272
=> docs: add chameleon onboarding guide

src/SharedComponents/AstroVirtualAssistant/AstroVirtualAssistant.tsx
Follow-up to https://github.com/RedHatInsights/astro-virtual-assistant-frontend/pull/287. The className should be applied to the Stack itself I believe
=> Move className prop to stack
